In [1]:
import numpy as np

In [2]:
import seaborn as sns

In [3]:
df=sns.load_dataset('mpg')

In [94]:
df.dropna(inplace=True)

In [96]:
y=df['mpg']
y.head()

0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
Name: mpg, dtype: float64

In [97]:
x=df.drop(df[['mpg','origin','name']],axis=1)

In [98]:
x.head()

cylinders  displacement  horsepower  weight  acceleration  model_year
0          8         307.0       130.0    3504          12.0          70
1          8         350.0       165.0    3693          11.5          70
2          8         318.0       150.0    3436          11.0          70
3          8         304.0       150.0    3433          12.0          70
4          8         302.0       140.0    3449          10.5          70

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
x_train,x_test,y_train,y_test =train_test_split(x,y, train_size=0.70)

In [61]:
x_train.head()

cylinders  displacement  horsepower  weight  acceleration  model_year
271          4         156.0       105.0    2745          16.7          78
206          4         140.0        72.0    2565          13.6          76
285          8         305.0       130.0    3840          15.4          79
283          6         232.0        90.0    3265          18.2          79
292          8         360.0       150.0    3940          13.0          79

In [62]:
from sklearn.linear_model import LinearRegression

In [63]:
obj=LinearRegression()

In [64]:
model=obj.fit(x_train,y_train)

In [31]:
model

LinearRegression()

In [55]:
y_pred=model.predict(x_test)

In [56]:
y_pred

array([12.36447528, 32.53064835, 33.7727032 , 25.33330264, 24.90144941,
       17.55700835, 20.80363339,  9.84410028, 25.92939112, 11.57870982,
       10.12603346, 28.50643509, 14.65993805, 19.49377675, 21.93377652,
       30.09943454, 23.72722411, 30.01155534, 30.92808878, 27.35395974,
       21.54025413, 26.21036438,  7.86328312, 17.31276647,  9.62580369,
       26.37239576, 26.70473864, 12.1204525 , 26.14377169, 26.48411861,
       35.61398719, 22.29161813, 30.50419534, 25.66034268, 11.331074  ,
       15.81285233, 21.11790638, 34.13521311, 20.19189161, 19.42326993,
       10.97518975, 28.64389507, 23.40829228, 22.46767651, 10.85919537,
       12.95374771, 28.16502698, 15.28055915, 21.5000439 , 27.03012118,
       18.34327049, 28.76796822, 26.40548791, 31.05417606, 27.41314931,
        4.72358588, 25.06836148, 26.50118219, 22.75290817, 19.32794561,
       18.06115724, 10.99085016, 12.13831684, 30.76391552, 27.26651487,
        9.56988008, 17.79391171, 35.22047539, 23.23674628, 17.44

In [57]:
import numpy as np
pred_y1=model.predict(np.array([[8,351.0,153.0,4154,13.5,71]]))

C:\Users\Suraj\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [58]:
pred_y1

array([11.43150452])

In [59]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [61]:
mean_absolute_error(y_test,y_pred)

2.5558434071117166

In [62]:
mean_squared_error(y_test,y_pred)

10.415032686140385

In [51]:
(mean_squared_error(y_test,y_pred))**(1/2)

3.2272329767372523

In [63]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.7893355623830067

In [64]:
from sklearn.metrics import r2_score
import numpy as np

# Calculate R-squared
r2 = r2_score(y_test, y_pred)

# Get the number of observations and predictors
N = len(y_test)
P = 5

# Calculate adjusted R-squared
adjusted_r2 = 1 - ((1 - r2) * (N - 1) / (N - P - 1))

print("Adjusted R-squared:", adjusted_r2)


Adjusted R-squared: 0.779930899989391


In [ ]:
######### practice ###########

In [1]:
import numpy as np 
import seaborn as sns

In [2]:
df=sns.load_dataset("car_crashes")
df.head()

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   
2   18.6     6.510    5.208          15.624       17.856       899.47   
3   22.4     4.032    5.824          21.056       21.280       827.34   
4   12.0     4.200    3.360          10.920       10.680       878.41   

   ins_losses abbrev  
0      145.08     AL  
1      133.93     AK  
2      110.35     AZ  
3      142.39     AR  
4      165.63     CA

In [3]:
df.dropna(inplace=True)

In [4]:
y=df["total"]
y.head()

0    18.8
1    18.1
2    18.6
3    22.4
4    12.0
Name: total, dtype: float64

In [8]:
x=df.drop(df[["total","abbrev"]],axis=1)
x.head()

speeding  alcohol  not_distracted  no_previous  ins_premium  ins_losses
0     7.332    5.640          18.048       15.040       784.55      145.08
1     7.421    4.525          16.290       17.014      1053.48      133.93
2     6.510    5.208          15.624       17.856       899.47      110.35
3     4.032    5.824          21.056       21.280       827.34      142.39
4     4.200    3.360          10.920       10.680       878.41      165.63

In [9]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.70)

In [17]:
#x_train,x_test,y_train,y_test =train_test_split(x,y, train_size=0.70)

In [18]:
x_train.head()

speeding  alcohol  not_distracted  no_previous  ins_premium  ins_losses
22     3.384    3.948          13.395       10.857      1110.61      152.26
37     4.224    3.328           8.576       11.520       804.71      104.61
47     4.452    3.498           8.692        9.116       890.03      111.62
40     9.082    9.799          22.944       19.359       858.97      116.29
29     4.060    3.480          10.092        9.628       746.54      120.21

In [19]:
y_train.head()

22    14.1
37    12.8
47    10.6
40    23.9
29    11.6
Name: total, dtype: float64

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
obj=LinearRegression()
obj

LinearRegression()

In [22]:
model=obj.fit(x_train,y_train)

In [83]:
model

LinearRegression()

In [24]:
y_predc=model.predict(x_test)
y_predc

array([18.13793263, 14.42748455,  8.09604256, 22.64917708, 16.77284062,
       12.67178945, 17.6758439 , 17.7221752 , 17.31029463, 14.20970721,
       16.2341818 , 16.04176272, 18.58292707, 16.12264443,  9.79329191,
       11.06195833])

In [28]:
from sklearn.metrics import mean_absolute_error

In [29]:
mean_absolute_error(y_test,y_predc)

0.8193756665565836

In [31]:
from sklearn.metrics import mean_squared_error

In [32]:
mean_squared_error(y_test,y_predc)

1.5022821318586186

In [34]:
(mean_squared_error(y_test,y_predc))**(1/2)

1.2256761937227216

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

In [35]:
from sklearn.metrics import r2_score

In [36]:
r2_score(y_test,y_predc)

0.8925213999743431

In [37]:
from sklearn.metrics import r2_score
import numpy as np

In [40]:
r2=r2_score(y_test,y_predc)
r2

0.8925213999743431

In [42]:
N = len(y_test)
N

16

In [45]:
P = 6

In [46]:
adjusted_r2 =  1-((1-r2)*(N-1)/(N-P-1))

In [47]:
adjusted_r2

0.8208689999572385