In [1]:
import numpy as np

In [2]:
np.__version__    # check version of numpy

'1.23.5'

In [12]:
test = np.array(['dfgdfg',45,75,234,75,2,47,5,734,654])   #  

In [13]:
test

array(['dfgdfg', '45', '75', '234', '75', '2', '47', '5', '734', '654'],
      dtype='<U11')

In [14]:
for i in test:
    print(i)

dfgdfg
45
75
234
75
2
47
5
734
654


In [15]:
for i in test:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [16]:
test.ndim    # type of dimensions(1D,2D,3D)

1

In [17]:
type(test)     # for checking type of test

numpy.ndarray

In [19]:
b = np.array((3,6,3,74)) # we can pass array in tuple also

In [20]:
b

array([ 3,  6,  3, 74])

In [21]:
type(b)

numpy.ndarray

In [25]:
a = np.array([56,34,86,345,86],dtype = 'int64') # we can provide datatype by
#dtype='int64' 

In [26]:
a

array([ 56,  34,  86, 345,  86], dtype=int64)

In [27]:
a = np.array([56,34,86,345,86],dtype = 'complex') # we can provide datatype by
#dtype='complex' 

In [29]:
a

array([ 56.+0.j,  34.+0.j,  86.+0.j, 345.+0.j,  86.+0.j])

In [30]:
import numpy as np

In [42]:
a = np.array([56,34,86,345,86],dtype = 'int')

In [43]:
a = np.array([56,34,86,345])

In [44]:
for i in a:
    print(i.dtype)

int32
int32
int32
int32


In [45]:
list(a)

[56, 34, 86, 345]

In [46]:
a

array([ 56,  34,  86, 345])

In [47]:
b=[4,66,77,77,99]      

In [48]:
type(b)

list

In [49]:
 b*2

[4, 66, 77, 77, 99, 4, 66, 77, 77, 99]

In [50]:
a*2       # we can apply operation directly

array([112,  68, 172, 690])

In [51]:
a/2

array([ 28. ,  17. ,  43. , 172.5])

In [52]:
a+5

array([ 61,  39,  91, 350])

In [53]:
a-5

array([ 51,  29,  81, 340])

In [54]:
a%5

array([1, 4, 1, 0], dtype=int32)

In [55]:
a

array([ 56,  34,  86, 345])

In [56]:
a.itemsize    # check size of item

4

In [30]:
a.itemsize*len(a)  # check size of total array

16

In [31]:
######################################

In [32]:
p = [ 56,  34,  86, 345,  86]

In [33]:
import sys

In [34]:
sys.getsizeof(345) # check size for list

28

In [35]:
sys.getsizeof(345)*len(p)  # check size for total list   

140

In [36]:
######################################################

In [37]:
## zero dimension #0 dim

In [57]:
a = np.array(85)

In [58]:
a

array(85)

In [40]:
a.ndim

0

In [41]:
#1D

In [59]:
a = np.array([45,875,36,5,4,75])

In [60]:
a.ndim

1

In [61]:
### for 2 dimension

In [73]:
a = np.array([[ 1,  2],[ 3,  4],[11, 55]])

In [74]:
a

array([[ 1,  2],
       [ 3,  4],
       [11, 55]])

In [75]:
a.ndim

2

In [77]:
details = np.array([['name','account'],['test','262652'],['sample','494949'],['test2323','sdafsdaf']])

In [78]:
details

array([['name', 'account'],
       ['test', '262652'],
       ['sample', '494949'],
       ['test2323', 'sdafsdaf']], dtype='<U8')

In [79]:
details.ndim

2

In [80]:
# for 3 dimension

In [81]:
a1 = np.array([[[1,2,3],[4,5,6]],[[100,200,300],[400,500,600]]])

In [82]:
a1

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[100, 200, 300],
        [400, 500, 600]]])

In [83]:
a1.ndim

3

In [84]:
###################################################################

In [85]:
## Fetch element from 1D,2D or 3D

In [88]:
a1

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[100, 200, 300],
        [400, 500, 600]]])

In [89]:
a1[0][1][2]

6

In [87]:
a1[0][0][0]
# |  |   |
# L  R   C


1

In [59]:
a1[1][0][1]

200

In [60]:
a1[1][1][2]

600

In [61]:
# check shape of array

In [62]:
a1.shape # (l,r,c)  or (z,r,c)

(2, 2, 3)

In [63]:
##############################################################

In [64]:
# How to change shape arrays

In [92]:
a = np.array([1,2,3,4,5,6,7,8])

In [93]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [94]:
a.shape

(8,)

In [95]:
a.ndim   # this is 1D format

1

In [96]:
8 -- 2*4,4*2,8*1,1*8,2*2*2

(16, 8, 8, 8, 8)

In [97]:
b=a.reshape(2,2,2) # converted into 2D format

In [98]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [99]:
b.ndim

3

In [100]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [101]:
c=a.reshape(2,2,2)   # converted into 3D format

In [102]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [103]:
c.ndim

3

In [104]:
#######################################################################

In [105]:
#***********by using zeros we can create 1D,2D 3D format************#

In [114]:
np.zeros(10)      #1D

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [115]:
np.zeros([4,4])      # 2D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [116]:
np.zeros([3,2,3])    #3D

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [117]:
#***********by using Ones we can create 1D,2D 3D format************#

In [118]:
np.ones(10)    #1D

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [119]:
np.ones([5,5])    # 2D


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [120]:
np.ones([2,5,5])   # 3D

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [122]:
a1 = np.ones(10,dtype='int')   # we can mention datatype by dtype='datatype_name'

In [123]:
a1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [124]:
a1.ndim

1

In [125]:
##********* multiply two matrix #################

In [126]:
a1 = np.array([[100,300],[500,400]])

In [127]:
a1

array([[100, 300],
       [500, 400]])

In [128]:
a2 = np.array([[12,45],[67,45]])                       

In [129]:
a2

array([[12, 45],
       [67, 45]])

In [130]:
100*12+300*67

21300

In [131]:
np.multiply(a1,a2)   # multification of two matrix

array([[ 1200, 13500],
       [33500, 18000]])

In [132]:
100*12+300*67

21300

In [133]:
######################### Dot product#####################

In [134]:
np.dot(a1,a2)

array([[21300, 18000],
       [32800, 40500]])

In [84]:
########### create range of no. by specific gap ######################

In [87]:
np.arange(1,11,dtype='int64')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [116]:
np.arange(1,11,3,dtype='int64')

array([ 1,  4,  7, 10], dtype=int64)

In [98]:
######### for create identity matrix #############

In [117]:
np.identity(5,dtype='int')  # if we want to create same order of matrix then we can use eye (no. of rows = no. of columns) 

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [120]:
np.eye(7,5)        # if we want to create different order of matrix then we can use eye (no. of rows != no. of columns)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [101]:
######### how to concept behind generating OTP or password ###############################

In [2]:
import numpy as np

In [135]:
np.random.randint(1000,9999)      # it is for 3 digit and upto 500

7342

In [136]:
np.random.randint(100,999)    # it is for 4 digit and from 5000 to 6000

912

In [143]:
np.random.rand(10)              # no. of sample as per requirement in range 0 to 1

array([3.56572144e-01, 3.21245243e-01, 3.32542967e-01, 9.53296717e-01,
       3.66719777e-01, 1.02601953e-01, 9.71265794e-04, 9.87681287e-01,
       5.09117865e-01, 1.12978563e-01])

In [144]:
#Statistics Operation on Numpy

In [145]:
#1.mean
#2.median
#3.mode
#4.std
#6.var


In [146]:
import numpy as np

In [147]:
a = np.array([34,9,3,97,3,86,34,76,45])   # 3,3,5,9,34,34,45,76,86,97,

In [148]:
a.mean()       # mean: as avg=sum of all element/ no. element

43.0

In [149]:
np.median(a)   # middle value if no. of element==odd   # but first we need to take in asc

34.0

In [150]:
a1 = np.array([4,9,15,17,19,23])  # avg of middle two value if no. of element==even

In [151]:
np.median(a1)

16.0

In [153]:
np.var(a1)           #  variance 

39.916666666666664

In [154]:
pip install numpy

^C
Note: you may need to restart the kernel to use updated packages.


In [156]:
import numpy as np

In [157]:
pip install scipy

^C
Note: you may need to restart the kernel to use updated packages.


In [158]:
from scipy import stats


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



KeyboardInterrupt



In [ ]:
a=[6,67787,88,7778,6]    # count of no. which max times present and fetch that no.

In [ ]:
stats.mode(a)

In [16]:
#ceil and floor

In [18]:
a2 = np.array([4.6,9.7,15.2,17.1,19,23])

In [19]:
np.ceil(a2)

array([ 5., 10., 16., 18., 19., 23.])

In [20]:
np.floor(a2)

array([ 4.,  9., 15., 17., 19., 23.])

In [21]:
a3 = np.array([-1.6,-4.6,-6.4,66.3,77.4])

In [22]:
np.ceil(a3)    #

array([-1., -4., -6., 67., 78.])

In [23]:
np.floor(a3)   # roundup towards  base

array([-2., -5., -7., 66., 77.])

In [24]:
a=np.array([3,55,77,88,999,77,77,77,55])

In [25]:
a

array([  3,  55,  77,  88, 999,  77,  77,  77,  55])

In [26]:
from scipy import stats

In [27]:
stats.mode(a)

C:\Users\admin\AppData\Local\Temp\ipykernel_3268\2714317682.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(a)


ModeResult(mode=array([77]), count=array([4]))

In [30]:
a='aaccccbbbbbb'

In [32]:
stats.mode(a)

C:\Users\admin\AppData\Local\Temp\ipykernel_3268\2714317682.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(a)
C:\Users\admin\AppData\Local\Temp\ipykernel_3268\2714317682.py:1: DeprecationWarning: Support for non-numeric arrays has been deprecated as of SciPy 1.9.0 and will be removed in 1.11.0. `pandas.DataFrame.mode` can be used instead, see https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mode.html.
  stats.mode(a)


ModeResult(mode=array(['aaccccbbbbbb'], dtype='<U12'), count=array([1]))

In [39]:
a='aaccccbbbbbbdddddddddddddddddddnnnnnnnnnnnnnn'

In [40]:
b={}
for i in a:
    if i not in b.keys():
        b[i]=a.count(i)
 
c=[]
for i,j in b.items():
    c.append(j)
    
h=sorted(c)[-2]
for i,j in b.items():
    if j==h:
        print(i,j)


n 14


In [126]:
n=0
for i in a:
    if n<a.count(i):
        n=a.count(i)


In [1]:
#################################################################################################3

In [5]:
import numpy as np

In [25]:
v=np.array([1,2,3,4,5,67,99], np.int16)

In [16]:
v=np.array((1,2,3,4,5,67,99), np.int16)

In [26]:
v

array([ 1,  2,  3,  4,  5, 67, 99], dtype=int16)

In [27]:
v[0]=66

In [28]:
v

array([66,  2,  3,  4,  5, 67, 99], dtype=int16)

In [19]:
v=np.array([[1,2,34,5],[1,2,3,4]])

In [20]:
v.shape

(2, 4)

In [21]:
v.size

8

In [35]:
v=np.array({1,2,3,4,5,67,99})

In [36]:
v

array({1, 2, 3, 4, 5, 67, 99}, dtype=object)

In [38]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [40]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
l=np.linspace(1,50,10)    #  10 random equal differed no. from 1 to 50

In [23]:
l

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [24]:
11.88888889-6.44444444

5.444444450000001

In [2]:
import numpy as np

In [4]:
np.empty((4,3))

array([[1.07011928e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.11260619e-306, 1.28103261e+161],
       [7.31814099e-042, 1.03979930e-042, 9.83876553e-072],
       [6.82015415e-038, 3.93222850e-061, 1.34679764e+165]])

In [45]:
np.empty_like(l)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [26]:
g=np.identity(45)

In [27]:
g.shape

(45, 45)

In [28]:
f=np.arange(9)

In [29]:
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
p=f.reshape(3,3)

In [31]:
f=np.arange(99)

In [32]:
g=f.reshape(3,33)

In [33]:
g

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [34]:
g=g.ravel()   # convert row and column into series

In [36]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
g.shape

(99,)

In [74]:
p

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [75]:
p.sum(axis=0)    # sum of verical nos.

array([ 9, 12, 15])

In [76]:
p.sum(axis=1)

array([ 3, 12, 21])

In [77]:
p.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [80]:
p

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [78]:
p.flat

In [79]:
for item in p.flat:
    print(item)

0
1
2
3
4
5
6
7
8


In [81]:
p.ndim

2

In [82]:
p.size

9

In [83]:
p.nbytes

36

In [54]:
c=np.array([11,2,33,99,45,1])

In [41]:
c

array([11,  2, 33, 99, 45,  1])

In [42]:
c.argmin()    # index of min value

5

In [43]:
c.argmax()    # index of min value

3

In [160]:
c.argsort()

array([[[0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1]]], dtype=int64)

In [161]:
p

NameError: name 'p' is not defined

In [46]:
p.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [47]:
p.argmin()

0

In [48]:
p.argmax()

8

In [49]:
p.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [50]:
p.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [51]:
p

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
q=np.array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
p+q

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [107]:
p*q                             

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [108]:
np.sqrt(p)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [109]:
p**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [110]:
p.max()

8

In [111]:
p.sum()

36

In [112]:
p.min()

0

In [113]:
p

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [114]:
np.where(p>5)

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [115]:
type(np.where(p>5))

tuple

In [117]:
np.count_nonzero(p)

8

In [118]:
np.nonzero(p)

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [119]:
import sys                                                                        

In [120]:
ch=[0,4,55,2]

In [121]:
num_a=np.array(ch)

In [122]:
num_a

array([ 0,  4, 55,  2])

In [123]:
sys.getsizeof(1)*len(num_a)

112

In [125]:
num_a.itemsize * len(num_a)

16

In [127]:
num_a.tolist()

[0, 4, 55, 2]